services:
  - type: web
    name: rokto-dorkar-web
    env: python
    buildCommand: |
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput
    startCommand: "gunicorn Blood.wsgi --bind 0.0.0.0:$PORT --workers 3"
    postDeployCommand: |
      python manage.py wait_for_db &&
      python manage.py migrate --noinput &&
      (python manage.py createsuperuser --noinput \
        --username $SUPERUSER_USERNAME \
        --email $SUPERUSER_EMAIL || true) &&
      python manage.py shell -c "from django.contrib.auth import get_user_model; \
        User = get_user_model(); \
        u = User.objects.get(username='$SUPERUSER_USERNAME'); \
        u.set_password('$SUPERUSER_PASSWORD'); \
        u.save()"
    healthCheckPath: /health/
    healthCheckTimeout: 120
    envVariables:
      DJANGO_SETTINGS_MODULE: "Blood.settings"
      CREATE_SUPERUSER: "true"
      SUPERUSER_USERNAME: "01739640467"
      SUPERUSER_EMAIL: "ahsanulanamsaboj1999@gmail.com"
      SUPERUSER_PASSWORD: "1999s@boj"
      # Add other required Django settings like:
      SECRET_KEY: "django-insecure-dcayu&u2ki=#ece4x*%pzp%3#&d8i95uut2@l^jss)ep7$d=+8"
      DEBUG: "False"
      ALLOWED_HOSTS: "rokto-dorkar.onrender.com"