# Generated by Django 5.0.6 on 2024-07-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_app', '0007_alter_person_person_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mobile_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
