# Generated by Django 5.1.2 on 2025-03-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_app', '0010_alter_person_age_alter_person_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
